version: '3.4'

services:
  trbopms:
    image: trbopms
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3300:3300
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/app.js"]
